/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.cadastro;



import controller.cadastro.HospedarController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class ReservaView extends javax.swing.JFrame {

    /**
     * Creates new form ReservaView
     */
    
    private final HospedarController controller;
    
    public ReservaView() throws SQLException {
        initComponents();
        controller = new HospedarController(this);
        iniciar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBoxHospede = new javax.swing.JComboBox<>();
        jLabelHospede = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jTextFieldHora = new javax.swing.JTextField();
        jLabelDataChegada = new javax.swing.JLabel();
        jTextFieldIdQuarto = new javax.swing.JTextField();
        jTextFieldDataCheckOut = new javax.swing.JTextField();
        jLabelServico = new javax.swing.JLabel();
        jComboBoxQuarto = new javax.swing.JComboBox<>();
        jLabelObservacao = new javax.swing.JLabel();
        jTextFieldNomeHospede1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelValor = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jButtonReservar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableReserva = new javax.swing.JTable();
        jTextFieldDataCheckIn = new javax.swing.JTextField();
        jLabelQtdDias = new javax.swing.JLabel();
        jTextFieldIdReserva = new javax.swing.JTextField();
        jLabelDataReserva = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelValor5 = new javax.swing.JLabel();
        jLabelData1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RESERVA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        jComboBoxHospede.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxHospedeItemStateChanged(evt);
            }
        });
        jComboBoxHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxHospedeActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxHospede, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 150, 30));

        jLabelHospede.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelHospede.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHospede.setText("NOME HÓSPEDE");
        getContentPane().add(jLabelHospede, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabelHora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHora.setText("HORA");
        getContentPane().add(jLabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));
        getContentPane().add(jTextFieldHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 150, 30));

        jLabelDataChegada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelDataChegada.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataChegada.setText("DATA CHECK OUT");
        getContentPane().add(jLabelDataChegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jTextFieldIdQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdQuartoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIdQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 180, 30));
        getContentPane().add(jTextFieldDataCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 150, 30));

        jLabelServico.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelServico.setForeground(new java.awt.Color(255, 255, 255));
        jLabelServico.setText("TIPO QUARTO");
        getContentPane().add(jLabelServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jComboBoxQuarto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxQuartoItemStateChanged(evt);
            }
        });
        jComboBoxQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxQuartoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 150, 30));

        jLabelObservacao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelObservacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelObservacao.setText("OBSERVAÇÃO");
        getContentPane().add(jLabelObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, -1, -1));

        jTextFieldNomeHospede1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeHospede1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNomeHospede1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 180, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(153, 153, 153));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 480, 220));

        jLabelValor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelValor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValor.setText("VALOR R$");
        getContentPane().add(jLabelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));
        getContentPane().add(jTextFieldValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 150, 30));

        jButtonReservar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonReservar.setText("RESERVAR");
        jButtonReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 480, 40));

        jTableReserva.setForeground(new java.awt.Color(51, 51, 51));
        jTableReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Reserva", "Hora Reserva", "Data Check In", "Data Check Out", "Id Hóspede", "Id Quarto", "Tipo Quarto", "Observação"
            }
        ));
        jScrollPane2.setViewportView(jTableReserva);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1050, 200));
        getContentPane().add(jTextFieldDataCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 150, 30));

        jLabelQtdDias.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelQtdDias.setForeground(new java.awt.Color(255, 255, 255));
        jLabelQtdDias.setText("ID RESERVA");
        getContentPane().add(jLabelQtdDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, -1, -1));

        jTextFieldIdReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdReservaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIdReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 340, 150, 30));

        jLabelDataReserva.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelDataReserva.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataReserva.setText("DATA CHECK IN");
        getContentPane().add(jLabelDataReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/menubase.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        jLabelValor5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelValor5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValor5.setText("HÓSPEDE");
        getContentPane().add(jLabelValor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabelData1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelData1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelData1.setText("DATA RESERVA");
        getContentPane().add(jLabelData1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservarActionPerformed
        
        try {
            this.controller.reservar();
        } catch (SQLException ex) {
            Logger.getLogger(ReservaView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonReservarActionPerformed

    private void jComboBoxQuartoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxQuartoItemStateChanged
        //Quando clica nas opções de quartos será executado mudança no valor
         this.controller.atualizaPreco();
         this.controller.atualizaId_quarto();
        
    }//GEN-LAST:event_jComboBoxQuartoItemStateChanged

    private void jTextFieldIdReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdReservaActionPerformed

    private void jComboBoxHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxHospedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxHospedeActionPerformed

    private void jComboBoxQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxQuartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxQuartoActionPerformed

    private void jTextFieldIdQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdQuartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdQuartoActionPerformed

    private void jTextFieldNomeHospede1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeHospede1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeHospede1ActionPerformed

    private void jComboBoxHospedeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxHospedeItemStateChanged
        // TODO add your handling code here:
        //this.controller.atualizaId_hospede();
    }//GEN-LAST:event_jComboBoxHospedeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ReservaView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ReservaView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public JButton getjButtonReservar() {
        return jButtonReservar;
    }

    public void setjButtonReservar(JButton jButtonReservar) {
        this.jButtonReservar = jButtonReservar;
    }

    public JComboBox<String> getjComboBoxHospede() {
        return jComboBoxHospede;
    }

    public void setjComboBoxHospede(JComboBox<String> jComboBoxHospede) {
        this.jComboBoxHospede = jComboBoxHospede;
    }

    public JComboBox<String> getjComboBoxQuarto() {
        return jComboBoxQuarto;
    }

    public void setjComboBoxQuarto(JComboBox<String> jComboBoxQuarto) {
        this.jComboBoxQuarto = jComboBoxQuarto;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabelData1() {
        return jLabelData1;
    }

    public void setjLabelData1(JLabel jLabelData1) {
        this.jLabelData1 = jLabelData1;
    }

    public JLabel getjLabelDataChegada() {
        return jLabelDataChegada;
    }

    public void setjLabelDataChegada(JLabel jLabelDataChegada) {
        this.jLabelDataChegada = jLabelDataChegada;
    }

    public JLabel getjLabelDataReserva() {
        return jLabelDataReserva;
    }

    public void setjLabelDataReserva(JLabel jLabelDataReserva) {
        this.jLabelDataReserva = jLabelDataReserva;
    }

    public JLabel getjLabelHora() {
        return jLabelHora;
    }

    public void setjLabelHora(JLabel jLabelHora) {
        this.jLabelHora = jLabelHora;
    }

    public JLabel getjLabelHospede() {
        return jLabelHospede;
    }

    public void setjLabelHospede(JLabel jLabelHospede) {
        this.jLabelHospede = jLabelHospede;
    }

    public JLabel getjLabelObservacao() {
        return jLabelObservacao;
    }

    public void setjLabelObservacao(JLabel jLabelObservacao) {
        this.jLabelObservacao = jLabelObservacao;
    }

    public JLabel getjLabelQtdDias() {
        return jLabelQtdDias;
    }

    public void setjLabelQtdDias(JLabel jLabelQtdDias) {
        this.jLabelQtdDias = jLabelQtdDias;
    }

    public JLabel getjLabelServico() {
        return jLabelServico;
    }

    public void setjLabelServico(JLabel jLabelServico) {
        this.jLabelServico = jLabelServico;
    }

    public JLabel getjLabelValor() {
        return jLabelValor;
    }

    public void setjLabelValor(JLabel jLabelValor) {
        this.jLabelValor = jLabelValor;
    }

    public JLabel getjLabelValor5() {
        return jLabelValor5;
    }

    public void setjLabelValor5(JLabel jLabelValor5) {
        this.jLabelValor5 = jLabelValor5;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTable getjTableReserva() {
        return jTableReserva;
    }

    public void setjTableReserva(JTable jTableReserva) {
        this.jTableReserva = jTableReserva;
    }

    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    public void setjTextArea1(JTextArea jTextArea1) {
        this.jTextArea1 = jTextArea1;
    }

    public JTextField getjTextFieldDataCheckIn() {
        return jTextFieldDataCheckIn;
    }

    public void setjTextFieldDataCheckIn(JTextField jTextFieldDataCheckIn) {
        this.jTextFieldDataCheckIn = jTextFieldDataCheckIn;
    }

    public JTextField getjTextFieldDataCheckOut() {
        return jTextFieldDataCheckOut;
    }

    public void setjTextFieldDataCheckOut(JTextField jTextFieldDataCheckOut) {
        this.jTextFieldDataCheckOut = jTextFieldDataCheckOut;
    }

    public JTextField getjTextFieldHora() {
        return jTextFieldHora;
    }

    public void setjTextFieldHora(JTextField jTextFieldHora) {
        this.jTextFieldHora = jTextFieldHora;
    }

    public JTextField getjTextFieldIdQuarto() {
        return jTextFieldIdQuarto;
    }

    public void setjTextFieldIdQuarto(JTextField jTextFieldIdQuarto) {
        this.jTextFieldIdQuarto = jTextFieldIdQuarto;
    }

    public JTextField getjTextFieldIdReserva() {
        return jTextFieldIdReserva;
    }

    public void setjTextFieldIdReserva(JTextField jTextFieldIdReserva) {
        this.jTextFieldIdReserva = jTextFieldIdReserva;
    }

    public JTextField getjTextFieldNomeHospede1() {
        return jTextFieldNomeHospede1;
    }

    public void setjTextFieldNomeHospede1(JTextField jTextFieldNomeHospede1) {
        this.jTextFieldNomeHospede1 = jTextFieldNomeHospede1;
    }

    public JTextField getjTextFieldValor() {
        return jTextFieldValor;
    }

    public void setjTextFieldValor(JTextField jTextFieldValor) {
        this.jTextFieldValor = jTextFieldValor;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReservar;
    private javax.swing.JComboBox<String> jComboBoxHospede;
    private javax.swing.JComboBox<String> jComboBoxQuarto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelData1;
    private javax.swing.JLabel jLabelDataChegada;
    private javax.swing.JLabel jLabelDataReserva;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelHospede;
    private javax.swing.JLabel jLabelObservacao;
    private javax.swing.JLabel jLabelQtdDias;
    private javax.swing.JLabel jLabelServico;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JLabel jLabelValor5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableReserva;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldDataCheckIn;
    private javax.swing.JTextField jTextFieldDataCheckOut;
    private javax.swing.JTextField jTextFieldHora;
    private javax.swing.JTextField jTextFieldIdQuarto;
    private javax.swing.JTextField jTextFieldIdReserva;
    private javax.swing.JTextField jTextFieldNomeHospede1;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables

    private void iniciar() throws SQLException {
     
 
      this.controller.atualizaServico();
      this.controller.atualizaPreco();
      this.controller.atualizaId_quarto();
      this.controller.atualizaHospede();
      //this.controller.atualizaId_hospede();
      //this.controller.atualizaNome();
//      this.controller.atualizaHospede();
     // this.controller.atualizaTabela();
      
    }

  
}
