/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class DeletarFuncionariosView extends javax.swing.JFrame {

    /**
     * Creates new form DeletarFuncionariosView
     */
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextFielNivelAcesso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabelDeletarFuncionarios = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIDFuncionario = new javax.swing.JTextField();
        jButtonDeletar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Atendente", "1"},
                {"Faxineiro", "2"},
                {"Manobrista", "3"},
                {"Cozinheiro", "4"},
                {null, null}
            },
            new String [] {
                "Cargo", "NIVEL ACESSO"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 210, 160));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DO FUNCIONÁRIO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, 50));

        jTextFielNivelAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielNivelAcessoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFielNivelAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 90, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NÍVEL DE ACESSO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 380, 50));

        jLabelDeletarFuncionarios.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelDeletarFuncionarios.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDeletarFuncionarios.setText("DELETAR FUNCIONÁRIOS");
        getContentPane().add(jLabelDeletarFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -20, 330, 80));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("INFORME O ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("INFORME O");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 380, 60));

        jTextFieldIDFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIDFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 90, 30));

        jButtonDeletar.setText("DELETAR");
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 160, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/cadastrologin.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
       
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jTextFieldIDFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDFuncionarioActionPerformed

    private void jTextFielNivelAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielNivelAcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielNivelAcessoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeletarFuncionariosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeletarFuncionariosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeletarFuncionariosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeletarFuncionariosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeletarFuncionariosView().setVisible(true);
            }
        });
    }

    public JTextField getjTextFielNivelAcesso() {
        return jTextFielNivelAcesso;
    }

    public void setjTextFielNivelAcesso(JTextField jTextFielNivelAcesso) {
        this.jTextFielNivelAcesso = jTextFielNivelAcesso;
    }

    public JTextField getjTextFieldIDFuncionario() {
        return jTextFieldIDFuncionario;
    }

    public void setjTextFieldIDFuncionario(JTextField jTextFieldIDFuncionario) {
        this.jTextFieldIDFuncionario = jTextFieldIDFuncionario;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDeletarFuncionarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFielNivelAcesso;
    private javax.swing.JTextField jTextFieldIDFuncionario;
    // End of variables declaration//GEN-END:variables
}
