/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.menu;

import controller.menu.MenuController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
//import view.informacoesHotel.TodosFuncionariosView;
//import view.informacoesHotel.TodosHospedesView;
import view.cadastro.CadastroHospede_NovoView;
import view.update.DeletarHospedeView;
//import view.cadastro.CadastroServicoCarroView;
//import view.cadastro.CadastroServicoCozinhaView;
//import view.cadastro.CadastroServicoDeQuartoView;


/**
 *
 * @author User
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    private final MenuController controller;
    public MenuView() {
        initComponents();
        this.controller = new MenuController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonTodosHospedes = new javax.swing.JButton();
        jButtonTodosFuncionários = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuReserva = new javax.swing.JMenu();
        jMenuItemFazeReserva = new javax.swing.JMenuItem();
        jMenuItemCancelarReserva = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemTodosHospedes = new javax.swing.JMenuItem();
        jMenuItemDeletaHospede = new javax.swing.JMenuItem();
        jMenuItemAdicionaHospede = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonTodosHospedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/BotãoHospedes.png"))); // NOI18N
        jButtonTodosHospedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTodosHospedesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTodosHospedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 440, 280));

        jButtonTodosFuncionários.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/BotãoFuncionarios3.png"))); // NOI18N
        jButtonTodosFuncionários.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTodosFuncionáriosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTodosFuncionários, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 440, 270));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/menubase.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1080, 710));

        jMenu5.setText("File");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenuBar2.add(jMenu5);

        jMenuReserva.setText("Reserva");

        jMenuItemFazeReserva.setText("Fazer Reserva");
        jMenuItemFazeReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFazeReservaActionPerformed(evt);
            }
        });
        jMenuReserva.add(jMenuItemFazeReserva);

        jMenuItemCancelarReserva.setText("Cancelar Reserva");
        jMenuItemCancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCancelarReservaActionPerformed(evt);
            }
        });
        jMenuReserva.add(jMenuItemCancelarReserva);

        jMenuBar2.add(jMenuReserva);

        jMenu1.setText("Hospedes");

        jMenuItemTodosHospedes.setText("Todos Hóspedes");
        jMenuItemTodosHospedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTodosHospedesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemTodosHospedes);

        jMenuItemDeletaHospede.setText("Deletar Hóspede");
        jMenuItemDeletaHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeletaHospedeActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDeletaHospede);

        jMenuItemAdicionaHospede.setText("Adicionar Hóspede");
        jMenuItemAdicionaHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdicionaHospedeActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAdicionaHospede);

        jMenuItem6.setText("Alterar Informações de Hóspede");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar2.add(jMenu1);

        jMenu4.setText("Check in/out");

        jMenuItem3.setText("Hóspedes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar2.add(jMenu4);

        jMenu2.setText("Realizar Serviços");

        jMenuItem1.setText("Serviço de Quarto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Serviço de Cozinha");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem4.setText("Serviço de Carro");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenuItemFazeReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFazeReservaActionPerformed
        try {
            // TODO add your handling code here:
            controller.navegarParaReserva();
        } catch (SQLException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemFazeReservaActionPerformed

    private void jMenuItemCancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCancelarReservaActionPerformed
        // TODO add your handling code here:
        //CancelarReservaView telaCancelaReserva = new CancelarReservaView();
        //telaCancelaReserva.setVisible(true);
    }//GEN-LAST:event_jMenuItemCancelarReservaActionPerformed

    private void jMenuItemTodosHospedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTodosHospedesActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_jMenuItemTodosHospedesActionPerformed

    private void jMenuItemDeletaHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeletaHospedeActionPerformed
        // TODO add your handling code here:
        DeletarHospedeView telaDeletaHospede = new DeletarHospedeView();
        telaDeletaHospede.setVisible(true);
       
    }//GEN-LAST:event_jMenuItemDeletaHospedeActionPerformed

    private void jMenuItemAdicionaHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdicionaHospedeActionPerformed
        // TODO add your handling code here:
        CadastroHospede_NovoView telaDeCadastroHospede;
        try {
            telaDeCadastroHospede = new CadastroHospede_NovoView();
            telaDeCadastroHospede.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
    }//GEN-LAST:event_jMenuItemAdicionaHospedeActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jButtonTodosHospedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTodosHospedesActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_jButtonTodosHospedesActionPerformed

    private void jButtonTodosFuncionáriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTodosFuncionáriosActionPerformed
       

    }//GEN-LAST:event_jButtonTodosFuncionáriosActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonTodosFuncionários;
    private javax.swing.JButton jButtonTodosHospedes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemAdicionaHospede;
    private javax.swing.JMenuItem jMenuItemCancelarReserva;
    private javax.swing.JMenuItem jMenuItemDeletaHospede;
    private javax.swing.JMenuItem jMenuItemFazeReserva;
    private javax.swing.JMenuItem jMenuItemTodosHospedes;
    private javax.swing.JMenu jMenuReserva;
    // End of variables declaration//GEN-END:variables
}
